### ISSUE TITLE
Upgrade 12.117.1

### ISSUE THREAD

**Issue by AidanTheBandit1** [YunoHost-Apps/misskey_ynh#118]
Misskey is currently on a pretty old version and has been updated a lot. The auto update branches don't seem to work. Is there any plans to update the main branch?

**Comment by memo-567** [comment]
Due to PostgreSQL >= 12 dependencies, Misskey >= 12.111.1 doesn't work on the current YunoHost version 4.3.6.3 (stable), since only PostgreSQL 11 is supported there.

PostgreSQL 13 is supported from YunoHost version >= 11.0.7 (Bullseye), which is currently only available as test version.

Since most users probably have YunoHost 4.3.6.3 installed, an update will not work there.

Therefore, all current changes that are still "on hold" in the Bullseye branch will probably be merged into the master branch when YunoHost >=11.0.7 (stable) is published.

**Comment by AidanTheBandit1** [comment]
Is there any estimate on when Yunohost 11 will be stable?

**Comment by memo-567** [comment]
Unfortunately, since I am not involved in the development, I cannot answer this question.

But, if you already have **YunoHost 11.0.7 (testing)** installed, you can try via SSH and the command "`sudo yunohost app upgrade misskey -u https://github.com/YunoHost-Apps/misskey_ynh/tree/bullseye --debug`" to update your Misskey installation to the latest here available version.

This should work fine, but since I'm probably the only one who tested this so far, I recommend a backup through webadmin beforehand so if something goes wrong, you can always go back.

**Comment by AidanTheBandit1** [comment]
I get this error when trying  to upgrade

**Comment by AidanTheBandit1** [comment]
I forgot to paste the link. Sorry https://hastebin.com/biheworotu.yaml

**Comment by memo-567** [comment]
This is strange.  I can't understand the lock file error.  I just tested it again last night:

An AMD64 system also, a fresh Misskey 12.110.1~ynh2 installation and an upgrade as described.

Everything went smooth.  Try to update your system before upgrade Misskey.

If this doesn't work, please test, if this works on a fresh Misskey 12.110.1 ~ ynh2 installation or install Misskey 12.117.1~ynh1 to another URI with "`sudo yunohost app install https://github.com/YunoHost-Apps/misskey_ynh/tree/bullseye --debug`".

**Comment by AidanTheBandit1** [comment]
Nope doesnt work and it gives the same error

**Comment by AidanTheBandit1** [comment]
I think its an issue with yarn

**Comment by memo-567** [comment]
That's really weird. It is known that updates don't work on ARM64 systems at the moment (Misskey code issues), but I don't know anything about problems with AMD64 systems.

**Comment by AidanTheBandit1** [comment]
I'm currently on an OVH server

**Comment by AidanTheBandit1** [comment]
When do you think this issue will be fixed?

**Comment by memo-567** [comment]
Unfortunately, since this is a Misskey issue, I don't know.

**Comment by AidanTheBandit1** [comment]
Ok

**Comment by AidanTheBandit1** [comment]
I got it to install but login screen loads forever

**Comment by ericgaspar** [comment]
#125  brings the last Misskey version on Bullseye.
Please reopen an issue with full logs if you still have problems.
